dist: trusty
filter_secrets: false
sudo: false

env:
  - ES_VERSION=6.6.2
  - ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
  - ELASTICSEARCH_PREFIX="test"

addons:
  postgresql: 9.6
  apt:
    packages:
      - libxml2-dev
      - libpq-dev
      - openjdk-7-jdk
      - python-dev
      - postgresql-9.6-postgis-2.3

services:
  - postgresql
  - couchdb

before_install:
  - psql -d postgres -c "ALTER USER postgres with encrypted password 'postgis';"
  - echo "*:*:*:postgres:postgis" >> ~/.pgpass
  - psql -d postgres -c "SET standard_conforming_strings = off;"
  - psql -d postgres -c "CREATE EXTENSION postgis;"
  - "pip install -e . --no-binary :all:"
  - pip install -r arches/install/requirements.txt
  - pip install -r arches/install/requirements_dev.txt
  - npm install -g wait-on
  - pip install coveralls
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - "./elasticsearch-${ES_VERSION}/bin/elasticsearch -v &"

cache:
  - apt
  - pip

after_success:
  - coveralls

before_script:
  - ./arches/install/ci_install/setup_couch.sh

language: 
  - python
  - node_js
python: 2.7.9
node_js: 10.8

matrix:
  include:
    - name: "Python tests"
      script:
        - wait-on http://localhost:9200/
        - python manage.py test tests --pattern="*.py" --settings="tests.test_settings"
      install:
    - name: "Cypress.io tests"
      install:
        - npm install -g cypress --save-dev
        - python manage.py packages -o setup_db
        - yarn install
      cache:
        npm: true
        directories:
          - ~/.cache
      script:
        - wait-on http://localhost:9200/
        - python manage.py runserver 0.0.0.0:8080 &
        - npm start & wait-on http://localhost:8080
        - npm run cy:run -- --record --parallel
        # after all tests finish running we need
        # to kill all background jobs (like "npm start &")
        - kill $(jobs -p) || true
