dist: trusty
language: python
filter_secrets: false

python:
  - 2.7

sudo: false

cache:
  - apt
  - pip

env:
  - ES_VERSION=6.6.2 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz

addons:
  postgresql: 9.6
  apt:
    # sources:
    #   - elasticsearch-6.x
    packages:
      #- elasticsearch
      - libxml2-dev
      - libpq-dev
      - openjdk-7-jdk
      - python-dev
      - postgresql-9.6-postgis-2.3

services:
  - postgresql
  - couchdb

before_install:
  - psql -d postgres -c "ALTER USER postgres with encrypted password 'postgis';"
  - echo "*:*:*:postgres:postgis" >> ~/.pgpass
  - psql -d postgres -c "SET standard_conforming_strings = off;"
  - psql -d postgres -c "CREATE EXTENSION postgis;"
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &

before_script: ./arches/install/ci_install/setup_couch.sh

install:
  - python setup.py install
  - pip install -r arches/install/requirements_dev.txt
  - pip install coveralls
  # - npm install -g yarn
  # - yarn install

script:
  - curl -v http://localhost:9200/
  #- wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - python manage.py test tests --pattern="*.py" --settings="tests.test_settings"

after_success:
  - coveralls